name = "strava-auth"
main = "worker/index.js"

compatibility_date = "2021-09-26"

workers_dev = true
keep_vars = true

[build]
watch_dir = "worker/"

[build.upload]
format = "modules"

[observability.logs]
enabled = true

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol = "http"
upstream_protocol = "https"