name = "strava-auth"
type = "javascript"

compatibility_date = "2021-09-26"

workers_dev = true
#route = "strava-auth.mountainash.workers.dev"

account_id = ""
zone_id = ""

[dev]
ip = "0.0.0.0"
port = 9000
local_protocol="http"
upstream_protocol="https"